"""
Lumped-parameter thermal model for datacenter rack/environment.

Governing equation:
    C * dT/dt = P(t) - hA * (T - T_ambient_eff)

Where:
    T              = rack/server temperature (K)
    T_ambient_eff  = effective ambient temperature with active cooling (K)
    P(t)           = heat generated by IT equipment (W)
    C              = effective thermal capacitance (J/K)
    hA             = effective heat-removal coefficient (W/K)
    dT/dt          = rate of temperature change (K/s)

Physics interpretation:
    Energy balance on a lumped thermal mass:
    - Energy in: P(t) from server dissipation
    - Energy out: hA * (T - T_ambient_eff) via convective/radiative cooling
    - Energy storage: C * dT/dt in the thermal mass

Modeling assumptions:
    1. Single lumped temperature node (not spatially distributed)
    2. Linear heat transfer: Q = hA * ΔT (empirical, valid for modest ΔT)
    3. Constant thermal properties (C, hA independent of temperature)
    4. Cooling intensity effect: reduced effective ambient by up to 10 K
       This is a simplification; real CRAC performance depends on mass flow,
       inlet/outlet conditions, and control dynamics. The 10 K reduction
       represents a rough "effective cooling boost" in this simplified model.
    5. No latent effects, phase changes, or radiation-only regimes
    6. Numerical integration via forward Euler (O(dt) error per step)

For real datacenter modeling, consider:
    - Spatially distributed thermal model (CFD/FVM)
    - Nonlinear/adaptive hA(T)
    - Multizone cooler dynamics
    - Humidity and air recirculation
"""

import numpy as np
from typing import Tuple, List, Dict, Optional


class ThermalModel:
    """
    Lumped-parameter thermal model for a datacenter rack or environment.
    
    Integrates the energy balance equation using forward Euler method.
    Deterministic: no random noise (use external functions to add stochasticity
    if needed for data generation).
    """
    
    def __init__(
        self,
        C: float,
        hA: float,
        T_ambient: float,
        T_initial: float,
        dt: float = 1.0,
    ):
        """
        Initialize the thermal model.
        
        Args:
            C (float): Thermal capacitance (J/K). Must be > 0.
                Physically: larger C → slower temperature response.
            hA (float): Heat removal coefficient (W/K). Must be > 0.
                Physically: larger hA → faster cooling efficiency.
            T_ambient (float): Ambient temperature (K). Must be finite and > 0.
                Typical value: 293.15 K (20°C) for datacenter ambient.
            T_initial (float): Initial rack temperature (K). Must be finite and > 0.
            dt (float): Simulation timestep (seconds). Must be > 0.
                Smaller dt → more accurate but slower simulation.
                For stability: dt should satisfy dt < 2 * C / hA.
                See _validate_stability_condition().
        
        Raises:
            ValueError: If any parameter is invalid.
        """
        self._validate_parameters(C, hA, T_ambient, T_initial, dt)
        
        self.C = C
        self.hA = hA
        self.T_ambient = T_ambient
        self.T = T_initial
        self.dt = dt
        
        # Check if timestep is reasonable for Euler stability
        # Explicit Euler for: dT/dt = (P - hA*dT) / C
        # Stability criterion: dt < 2*C/hA (Courant condition)
        self._check_euler_stability()
        
        # Logging
        self.history = {
            'time': [],
            'temperature': [],
            'power': [],
            'cooling_intensity': [],
            'inlet_temperature': [],
            'outlet_temperature': [],
            'heat_removal': [],
        }
        self.time_elapsed = 0.0
    
    @staticmethod
    def _validate_parameters(C, hA, T_ambient, T_initial, dt):
        """
        Validate all model parameters are physically meaningful.
        
        Raises:
            ValueError: If any parameter fails validation.
        """
        if C <= 0:
            raise ValueError(f"Thermal capacitance C must be > 0, got {C}")
        if hA <= 0:
            raise ValueError(f"Heat removal coefficient hA must be > 0, got {hA}")
        if T_ambient <= 0 or not np.isfinite(T_ambient):
            raise ValueError(f"Ambient temperature T_ambient must be > 0 and finite, got {T_ambient}")
        if T_initial <= 0 or not np.isfinite(T_initial):
            raise ValueError(f"Initial temperature T_initial must be > 0 and finite, got {T_initial}")
        if dt <= 0:
            raise ValueError(f"Timestep dt must be > 0, got {dt}")
    
    def _check_euler_stability(self):
        """
        Check if timestep satisfies explicit Euler stability criterion.
        
        For the ODE: dT/dt = (P - hA*(T - T_amb)) / C
        Linearized around equilibrium: dT/dt ≈ -hA/C * dT
        Explicit Euler stability: dt < 2*C/hA
        
        If violated, issue a warning (not an error, since user may accept larger errors).
        """
        stability_limit = 2.0 * self.C / self.hA
        if self.dt >= stability_limit:
            print(
                f"WARNING: timestep dt={self.dt} >= stability limit {stability_limit:.2f}. "
                f"Simulation may exhibit oscillations or divergence. "
                f"Recommend dt < {stability_limit:.2f}."
            )
    
    @property
    def current_temperature(self) -> float:
        """Return current rack temperature in Kelvin."""
        return self.T
    
    @property
    def current_temperature_celsius(self) -> float:
        """Return current rack temperature in Celsius."""
        return self.T - 273.15
    
    def step(
        self,
        power: float,
        cooling_intensity: float,
        T_ambient: Optional[float] = None,
    ) -> float:
        """
        Advance thermal model by one timestep using forward Euler.
        
        Energy balance:
            C * dT/dt = power - hA * (T - T_ambient_eff)
        
        Where:
            T_ambient_eff = T_ambient - cooling_intensity * cooling_boost
        
        Cooling intensity parameter (0 to 1):
            - 0.0: no active cooling (only passive heat removal at T_ambient)
            - 1.0: maximum cooling (T_ambient reduced by cooling_boost)
        
        Cooling boost = 10 K:
            This is a SIMPLIFICATION representing the effective temperature
            reduction achieved by active cooling (fans, CRAC, etc.). Real systems
            have complex dependencies on flow rate, inlet conditions, and control.
            This simplified model uses a constant 10 K reduction for tractability.
        
        Args:
            power (float): Server power dissipation (W). Must be >= 0.
            cooling_intensity (float): Cooling intensity [0, 1]. 1 = max cooling.
            T_ambient (float, optional): Update ambient temperature if provided (K).
        
        Returns:
            float: New rack temperature (K).
        
        Raises:
            ValueError: If power < 0, cooling_intensity not in [0, 1], or T_ambient invalid.
        """
        if power < 0:
            raise ValueError(f"Power must be >= 0, got {power}")
        if not (0.0 <= cooling_intensity <= 1.0):
            raise ValueError(
                f"cooling_intensity must be in [0, 1], got {cooling_intensity}"
            )
        
        # Update ambient if provided
        if T_ambient is not None:
            if T_ambient <= 0 or not np.isfinite(T_ambient):
                raise ValueError(
                    f"Updated T_ambient must be > 0 and finite, got {T_ambient}"
                )
            self.T_ambient = T_ambient
        
        # Effective ambient temperature with active cooling
        # cooling_boost = 10 K is a modeling choice (simplified CRAC performance)
        cooling_boost = 10.0  # K
        T_ambient_eff = self.T_ambient - cooling_intensity * cooling_boost
        
        # Energy balance ODE: C * dT/dt = power - hA * (T - T_ambient_eff)
        # Rearrange: dT/dt = (power - hA * (T - T_ambient_eff)) / C
        dT_dt = (power - self.hA * (self.T - T_ambient_eff)) / self.C
        
        # Forward Euler step: T_new = T + dT/dt * dt
        T_new = self.T + dT_dt * self.dt
        
        # Calculate heat removal for logging
        heat_removal = self.hA * (self.T - T_ambient_eff)
        
        # Update state
        self.T = T_new
        self.time_elapsed += self.dt
        
        # Log
        self.history['time'].append(self.time_elapsed)
        self.history['temperature'].append(self.T)
        self.history['power'].append(power)
        self.history['cooling_intensity'].append(cooling_intensity)
        self.history['inlet_temperature'].append(T_ambient_eff)
        self.history['outlet_temperature'].append(self.T)
        self.history['heat_removal'].append(heat_removal)
        
        return self.T
    
    def run_scenario(
        self,
        power_sequence: np.ndarray,
        cooling_sequence: np.ndarray,
        T_ambient_sequence: Optional[np.ndarray] = None,
    ) -> Dict[str, np.ndarray]:
        """
        Run a simulation scenario with time-varying power and cooling.
        
        Args:
            power_sequence (np.ndarray): Server power over time (W), shape (n_steps,).
                All values must be >= 0.
            cooling_sequence (np.ndarray): Cooling intensity over time [0, 1], shape (n_steps,).
            T_ambient_sequence (np.ndarray, optional): Ambient temp over time (K), shape (n_steps,).
                If None, uses constant self.T_ambient.
        
        Returns:
            dict: History with keys: 'time', 'temperature', 'power', 'cooling_intensity',
                  'inlet_temperature', 'outlet_temperature', 'heat_removal'.
                  All values are numpy arrays.
        
        Raises:
            AssertionError: If sequence lengths do not match.
        """
        assert len(power_sequence) == len(cooling_sequence), \
            "power_sequence and cooling_sequence must have same length"
        
        if T_ambient_sequence is not None:
            assert len(T_ambient_sequence) == len(power_sequence), \
                "T_ambient_sequence must have same length as power_sequence"
        
        # Reset history
        self.history = {
            'time': [],
            'temperature': [],
            'power': [],
            'cooling_intensity': [],
            'inlet_temperature': [],
            'outlet_temperature': [],
            'heat_removal': [],
        }
        self.time_elapsed = 0.0
        
        for i, power in enumerate(power_sequence):
            cooling = cooling_sequence[i]
            T_amb = T_ambient_sequence[i] if T_ambient_sequence is not None else None
            self.step(power, cooling, T_amb)
        
        # Convert lists to numpy arrays
        return {
            k: np.array(v) for k, v in self.history.items()
        }
    
    def reset(self, T_initial: float):
        """
        Reset the model to an initial temperature and clear history.
        
        Args:
            T_initial (float): Initial temperature (K). Must be > 0 and finite.
        
        Raises:
            ValueError: If T_initial is invalid.
        """
        if T_initial <= 0 or not np.isfinite(T_initial):
            raise ValueError(
                f"T_initial must be > 0 and finite, got {T_initial}"
            )
        self.T = T_initial
        self.time_elapsed = 0.0
        self.history = {
            'time': [],
            'temperature': [],
            'power': [],
            'cooling_intensity': [],
            'inlet_temperature': [],
            'outlet_temperature': [],
            'heat_removal': [],
        }
